### PR TITLE
improve freezable class

### PR DESCRIPTION
**Pull request by wakamex**
use Freezable as a class mixin instead of a decorator, allowing static typing of methods without stubbing

### CODE REVIEW

**Comment by dpaiton** [comment]
Can you add a PR description? I'm not sure what the outcome of these changes should be.

**Review by dpaiton — APPROVED** [review]
Add a todo to remove the need to include type stubs for e.g. `def freeze(...` in any class that has the freezable decorator. Otherwise this is a great improvement!

**Comment by wakamex** [comment]
no more type stubs necessary!

image

**Comment by wakamex** [comment]
forgot you were going to review again @dpaiton even though I just requested a review 15 mins ago. we can revert, or add fixes on top.

**Pull request merged**
